apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonos-api-nocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonos-api-nocode
  template:
    metadata:
      labels:
        app: sonos-api-nocode
    spec:
      containers:
      - name: sonos-nocode-api
        image: brianapley/sonos-api-nocode
        imagePullPolicy: Always
        ports:
        - containerPort: 1880
